import { MoviesType } from "./Movies.type";

export const dummy: MoviesType = {
    dates: {
        maximum: "2023-11-01",
        minimum: "2023-09-20",
    },
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: "/wl4NWiZwpzZH67HiDgpDImLyds9.jpg",
            genre_ids: [28, 12, 53],
            id: 299054,
            original_language: "en",
            original_title: "Expend4bles",
            overview:
                "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
            popularity: 2741.244,
            poster_path: "/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg",
            release_date: "2023-09-15",
            title: "Expend4bles",
            video: false,
            vote_average: 6.425,
            vote_count: 477,
        },
        {
            adult: false,
            backdrop_path: "/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg",
            genre_ids: [27, 53],
            id: 507089,
            original_language: "en",
            original_title: "Five Nights at Freddy's",
            overview:
                "Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
            popularity: 3635.108,
            poster_path: "/A4j8S6moJS2zNtRR8oWF08gRnL5.jpg",
            release_date: "2023-10-25",
            title: "Five Nights at Freddy's",
            video: false,
            vote_average: 8.637,
            vote_count: 519,
        },
        {
            adult: false,
            backdrop_path: "/tC78Pck2YCsUAtEdZwuHYUFYtOj.jpg",
            genre_ids: [28, 53, 80],
            id: 926393,
            original_language: "en",
            original_title: "The Equalizer 3",
            overview:
                "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
            popularity: 2546.535,
            poster_path: "/b0Ej6fnXAP8fK75hlyi2jKqdhHz.jpg",
            release_date: "2023-08-30",
            title: "The Equalizer 3",
            video: false,
            vote_average: 7.316,
            vote_count: 1142,
        },
        {
            adult: false,
            backdrop_path: "/azD31DjpV3PJfjF3h72LVw2WCSD.jpg",
            genre_ids: [27],
            id: 807172,
            original_language: "en",
            original_title: "The Exorcist: Believer",
            overview:
                "When his daughter and her friend show signs of demonic possession, it unleashes a chain of events that forces single father, Victor Fielding, to confront the nadir of evil. Terrified and desperate, he seeks out the only person alive who's witnessed anything like it before.",
            popularity: 1181.232,
            poster_path: "/qVKirUdmoex8SdfUk8WDDWwrcCh.jpg",
            release_date: "2023-10-04",
            title: "The Exorcist: Believer",
            video: false,
            vote_average: 5.991,
            vote_count: 272,
        },
        {
            adult: false,
            backdrop_path: "/dZbLqRjjiiNCpTYzhzL2NMvz4J0.jpg",
            genre_ids: [27, 53],
            id: 951491,
            original_language: "en",
            original_title: "Saw X",
            overview:
                "Between the events of 'Saw' and 'Saw II', a sick and desperate John Kramer travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer, only to discover the entire operation is a scam to defraud the most vulnerable. Armed with a newfound purpose, the infamous serial killer returns to his work, turning the tables on the con artists in his signature visceral way through devious, deranged, and ingenious traps.",
            popularity: 1261.823,
            poster_path: "/aQPeznSu7XDTrrdCtT5eLiu52Yu.jpg",
            release_date: "2023-09-26",
            title: "Saw X",
            video: false,
            vote_average: 7.285,
            vote_count: 486,
        },
        {
            adult: false,
            backdrop_path: "/mRGmNnh6pBAGGp6fMBMwI8iTBUO.jpg",
            genre_ids: [27, 9648, 53],
            id: 968051,
            original_language: "en",
            original_title: "The Nun II",
            overview:
                "In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.",
            popularity: 1331.357,
            poster_path: "/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg",
            release_date: "2023-09-06",
            title: "The Nun II",
            video: false,
            vote_average: 6.968,
            vote_count: 1154,
        },
        {
            adult: false,
            backdrop_path: "/pA3vdhadJPxF5GA1uo8OPTiNQDT.jpg",
            genre_ids: [28, 18],
            id: 678512,
            original_language: "en",
            original_title: "Sound of Freedom",
            overview:
                "The story of Tim Ballard, a former US government agent, who quits his job in order to devote his life to rescuing children from global sex traffickers.",
            popularity: 1551.418,
            poster_path: "/qA5kPYZA7FkVvqcEfJRoOy4kpHg.jpg",
            release_date: "2023-07-03",
            title: "Sound of Freedom",
            video: false,
            vote_average: 8.119,
            vote_count: 1025,
        },
        {
            adult: false,
            backdrop_path: "/r7DuyYJ0N3cD8bRKsR5Ygq2P7oa.jpg",
            genre_ids: [12, 28, 18],
            id: 980489,
            original_language: "en",
            original_title: "Gran Turismo",
            overview:
                "The ultimate wish-fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.",
            popularity: 1436.813,
            poster_path: "/51tqzRtKMMZEYUpSYkrUE7v9ehm.jpg",
            release_date: "2023-08-09",
            title: "Gran Turismo",
            video: false,
            vote_average: 8.066,
            vote_count: 1193,
        },
        {
            adult: false,
            backdrop_path: "/h7BoGo4NhckWRiMUCi3Qr8GwBDA.jpg",
            genre_ids: [28, 80, 18, 53],
            id: 1039690,
            original_language: "en",
            original_title: "Desperation Road",
            overview:
                "After 11 years in a Mississippi state prison, Russell Gaines struggles to leave his past sins behind him as he returns home to his stoic father, Mitchell. One fateful night he meets Maben, a young mother with nothing but a stolen gun and a murdered police deputy to her name. Desperate and on the run, Russell and Maben must trust one another to escape their own circumstances, before the truths of their intertwined violent past threatens to destroy them.",
            popularity: 527.22,
            poster_path: "/tPyj6Gii1HrnzCbJXEF7JdSFkQ8.jpg",
            release_date: "2023-10-19",
            title: "Desperation Road",
            video: false,
            vote_average: 6.75,
            vote_count: 12,
        },
        {
            adult: false,
            backdrop_path: "/H6j5smdpRqP9a8UnhWp6zfl0SC.jpg",
            genre_ids: [28, 878, 12],
            id: 565770,
            original_language: "en",
            original_title: "Blue Beetle",
            overview:
                "Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.",
            popularity: 822.711,
            poster_path: "/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg",
            release_date: "2023-08-16",
            title: "Blue Beetle",
            video: false,
            vote_average: 7.052,
            vote_count: 1406,
        },
        {
            adult: false,
            backdrop_path: "/zgQQF04u3OgNBJqClRNby1FPz9s.jpg",
            genre_ids: [16, 10751, 28, 878],
            id: 893723,
            original_language: "en",
            original_title: "PAW Patrol: The Mighty Movie",
            overview:
                "A magical meteor crash-lands in Adventure City, gives the PAW Patrol pups superpowers, and transforms them into The Mighty Pups. When the Patrol's archrival Humdinger breaks out of jail and teams up with mad scientist Victoria Vance to steal the powers for themselves, the Mighty Pups must save Adventure City and stop the supervillains before it's too late.",
            popularity: 772.128,
            poster_path: "/aTvePCU7exLepwg5hWySjwxojQK.jpg",
            release_date: "2023-09-21",
            title: "PAW Patrol: The Mighty Movie",
            video: false,
            vote_average: 7.227,
            vote_count: 66,
        },
        {
            adult: false,
            backdrop_path: "/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg",
            genre_ids: [28, 53, 80],
            id: 762430,
            original_language: "en",
            original_title: "Retribution",
            overview:
                "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
            popularity: 962.165,
            poster_path: "/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg",
            release_date: "2023-08-23",
            title: "Retribution",
            video: false,
            vote_average: 6.979,
            vote_count: 512,
        },
        {
            adult: false,
            backdrop_path: "/iIvQnZyzgx9TkbrOgcXx0p7aLiq.jpg",
            genre_ids: [27, 53],
            id: 1008042,
            original_language: "en",
            original_title: "Talk to Me",
            overview:
                "When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.",
            popularity: 913.935,
            poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
            release_date: "2023-07-26",
            title: "Talk to Me",
            video: false,
            vote_average: 7.193,
            vote_count: 1584,
        },
        {
            adult: false,
            backdrop_path: "/jP3FatCTHc460ZGW57q9ypTdBqu.jpg",
            genre_ids: [53, 878, 28],
            id: 937249,
            original_language: "en",
            original_title: "57 Seconds",
            overview:
                "When a tech blogger lands an interview with a tech guru and stops an attack on him, he finds a mysterious ring that takes him back 57 seconds into the past.",
            popularity: 590.167,
            poster_path: "/dfS5qHWFuXyZQnwYREwb7N4qU5p.jpg",
            release_date: "2023-09-29",
            title: "57 Seconds",
            video: false,
            vote_average: 5.6,
            vote_count: 131,
        },
        {
            adult: false,
            backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
            genre_ids: [35, 12, 14],
            id: 346698,
            original_language: "en",
            original_title: "Barbie",
            overview:
                "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
            popularity: 665.641,
            poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
            release_date: "2023-07-19",
            title: "Barbie",
            video: false,
            vote_average: 7.221,
            vote_count: 5625,
        },
        {
            adult: false,
            backdrop_path: "/8KJMOKyl9rpgb9ELEwhfBMIaTHw.jpg",
            genre_ids: [10751, 16, 14, 35],
            id: 1139087,
            original_language: "en",
            original_title: "Once Upon a Studio",
            overview:
                "Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.",
            popularity: 501.214,
            poster_path: "/hr8ZtwdbtjBquxlTCrczr685K5T.jpg",
            release_date: "2023-09-24",
            title: "Once Upon a Studio",
            video: false,
            vote_average: 8.807,
            vote_count: 158,
        },
        {
            adult: false,
            backdrop_path: "/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
            genre_ids: [10751, 16, 14, 10402, 35, 12],
            id: 354912,
            original_language: "en",
            original_title: "Coco",
            overview:
                "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.",
            popularity: 750.136,
            poster_path: "/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
            release_date: "2017-10-27",
            title: "Coco",
            video: false,
            vote_average: 8.221,
            vote_count: 17909,
        },
        {
            adult: false,
            backdrop_path: "/2fAnbhiwqPiu0XHA98nZrPckPgv.jpg",
            genre_ids: [27, 14, 53],
            id: 675531,
            original_language: "en",
            original_title: "Dark Harvest",
            overview:
                "In a cursed town, the annual harvest becomes a brutal battle for survival. On Halloween 1963, Sawtooth Jack, a terrifying legend, rises from the cornfields, threatening the town’s children. Groups of boys unite to defeat the murderous scarecrow before midnight. Richie, a rebellious outcast, joins the run, motivated by his brother’s previous victory. As the hunt progresses, Richie makes a shocking discovery and faces a pivotal choice to break the relentless cycle.",
            popularity: 492.685,
            poster_path: "/sFBDjWdw8gHSI2dMivP7H52iwvp.jpg",
            release_date: "2023-10-11",
            title: "Dark Harvest",
            video: false,
            vote_average: 5.816,
            vote_count: 76,
        },
        {
            adult: false,
            backdrop_path: "/eSsMzJpzAwCa69tm6Wco2il44aJ.jpg",
            genre_ids: [28, 80, 18, 53],
            id: 939335,
            original_language: "en",
            original_title: "Muzzle",
            overview:
                "LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a chokehold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.",
            popularity: 528.991,
            poster_path: "/qXChf7MFL36BgoLkiB3BzXiwW82.jpg",
            release_date: "2023-09-29",
            title: "Muzzle",
            video: false,
            vote_average: 6.326,
            vote_count: 43,
        },
        {
            adult: false,
            backdrop_path: "/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg",
            genre_ids: [10749, 18],
            id: 820525,
            original_language: "en",
            original_title: "After Everything",
            overview:
                "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
            popularity: 457.321,
            poster_path: "/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg",
            release_date: "2023-09-13",
            title: "After Everything",
            video: false,
            vote_average: 6.922,
            vote_count: 392,
        },
    ],
    total_pages: 102,
    total_results: 2033,
};
